### ISSUE TITLE
HU: Navegar desde el navbar

### ISSUE THREAD

**Issue by yamilyami** [yamilyami/Biodigestor-Houssay#34]
Como usuario, quiero tener un navbar en la parte superior de la página de inicio para navegar fácilmente a otras secciones del sitio.

**Comment by yamilyami** [comment]
Mejorar el tema de las letras que se pierden

**Comment by Paz-Santangelo** [comment]
Ya realicé el re-diseño del navbar y el merge a la rama develop.
